copy locas   (ID,CODE,NAME,ABBR,ZIP,COUNTRY,PRFCT,ADDR1,ADDR2,TEL,FAX,MAIL,REMARK,EXPIREDATE,PERSONS_ID_UPD,UPDATE_IP,CREATED_AT,UPDATED_AT)  FROM '/mnt/c/ubuntu/RRRP/init/v10data/TEST_LOCAS.csv' CSV HEADER ;

copy sects( ID,LOCAS_ID_SECT,PERSONS_ID_UPD,UPDATE_IP,CREATED_AT,UPDATED_AT,EXPIREDATE,REMARK) FROM '/mnt/c/ubuntu/RRRP/init/v10data/TEST_SECTS.csv' CSV HEADER ;

copy persons(ID,CODE,NAME,EMAIL,REMARK,EXPIREDATE,PERSONS_ID_UPD,UPDATE_IP,CREATED_AT,UPDATED_AT,SCRLVS_ID,SECTS_ID,USRGRPS_ID ) FROM '/mnt/c/ubuntu/RRRP/init/v10data/TEST_PERSONS.csv' CSV HEADER ;



copy POBJGRPS(ID,POBJECTS_ID,USRGRPS_ID,NAME,REMARK,PERSONS_ID_UPD,UPDATE_IP,CREATED_AT,EXPIREDATE,UPDATED_AT,contents) FROM '/mnt/c/ubuntu/RRRP/init/v10data/POBJGRPS.csv' CSV HEADER ;
