# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a7e686e0b48f492f466da0d31ba999db5502eb8aa874792e1abd2d84a25e0996f98b9a662d3d01434e649251f6ff8bf889e754e4fc1e846f8d60b5d38bf515e

test:
  secret_key_base: a11e85d9aea898fddc48c5feb2611aa1bd852ce4634fe5e6921b1ee3200c6ec8ff89b66f962c9cbe7caa6e62970a29daca53a3001f794fbb664e17e12beba457

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
