
create SEQUENCE  sio.SIO_R_BLKTBS_SEQ
;
create SEQUENCE  sio.SIO_R_BLKUKYS_SEQ
;
create SEQUENCE  sio.SIO_R_BUTTONS_SEQ
;
create SEQUENCE  sio.SIO_R_CHILSCREENS_SEQ
;
create SEQUENCE  sio.SIO_R_FIELDCODES_SEQ
;
create SEQUENCE  sio.SIO_R_LOCAS_SEQ
;
create SEQUENCE  sio.SIO_R_PERSONS_SEQ
;
create SEQUENCE  sio.SIO_R_POBJECTS_SEQ
;
create SEQUENCE  sio.SIO_R_POBJGRPS_SEQ
;
create SEQUENCE  sio.SIO_R_PRJNOS_SEQ
;
create SEQUENCE  sio.SIO_R_REPORTS_SEQ
;
create SEQUENCE  sio.SIO_R_SCREENFIELDS_SEQ
;
create SEQUENCE  sio.SIO_R_SCREENS_SEQ
;
create SEQUENCE  sio.SIO_R_SCRLVS_SEQ
;
create SEQUENCE  sio.SIO_R_SECTS_SEQ
;
create SEQUENCE  sio.SIO_R_TBLFIELDS_SEQ
;
create SEQUENCE  sio.SIO_R_TBLINKFLDS_SEQ
;
create SEQUENCE  sio.SIO_R_TBLINKS_SEQ
;
create SEQUENCE  sio.SIO_R_USEBUTTONS_SEQ
;
create SEQUENCE  sio.SIO_R_USRGRPS_SEQ
;
create SEQUENCE  sio.SIO_SCR_POBJECTS_SEQ
;
create SEQUENCE  sio.SIO_VIEW_POBJECTS_SEQ
;
create SEQUENCE  sio.SIO_SFD_POBJECTS_SEQ
;
  
create SEQUENCE  sio.SIO_TBL_POBJECTS_SEQ
;
create SEQUENCE  SIO_R_RUBYCODINGS_SEQ
;
 