(function(z){
'use strict';var s7=function(a){z.L.call(this);this.aa(a)},o5a=function(a,b){this.user=a;this.quotes=b},p5a=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},t7=function(a){return a.PB.best||null},u7=function(a,b){b=b.filter(function(a){return"anon"!=a.nb()});b=z.lb(b,function(a){return a.nb()},a);return z.rb(b).map(function(a){return new o5a(a[0].bc(),a)},a)},q5a=function(a,b,c,d){return(0,z.vd)(a.$t[b.name]||
[],function(a){return a.Dd()==c&&a.Ae()==d})},v7=function(){this.JH=1},w7=function(a){z.Xh.call(this);this.aa(a)},r5a=function(a,b){return z.K(a,"slots",b)},s5a=function(a,b){return z.K(a,"requestContext",b)},x7=function(a){z.L.call(this);this.aa(a)},y7=function(a){return z.J(a,"inResponseToMediaResource")},z7=function(a){return z.J(a,"mediumQuote")},t5a=function(a,b){a.FQ=b;return a},A7=function(a,b){return t7(a)?z.iD(t7(a)).filter(function(a){return this.z5(a)==b},a):[]},u5a=function(a,b,c){c=c.sy;
b=b.getAttribute("name").split(" ");var d=z.Gb(b);a=(a.$t[c.name]||[]).filter(function(a){return d[a.Xi()]});return a.length?z.pva(a):null},v5a=function(a,b,c,d){b=q5a(a,b,c,d);return u7(a,b)},w5a=function(a,b){var c=0;(a.$t[b]||[]).forEach(function(a){"anon"==a.nb()&&(c+=a.Ne())});return c},x5a=function(a){var b=z.kN(a.lk.Ct,a.lk.Xr(),a.rm.Ct,a.rm.Xr()).Ia().trim();0<a.lk.Xr()&&(b="…"+b);var c=z.UD(a.yc,a.rm.Ct);a.rm.Xr()<c.Ia().length&&(b+="…");return b},y5a=function(a){var b=z.NB(a.Uya),c=a.lk.Ct,
d=c?b.indexOf(c):-1,e=(c=a.rm.Ct)?b.indexOf(c):-1;if(-1==d||-1==e)return"";for(c=[];d<=e;d++)c.push(z.UD(a.yc,b[d]));b=z.Ra(c);a=z.Qt(c.indexOf(c[0]),a.lk.Xr(),c.indexOf(b),a.rm.Xr(),!1);return z.Lja(new z.Dt(z.Mm,z.rDa),c,a,!0)},z5a=function(a,b,c){var d=a.ma.la(z.ZCa,{postId:b},{filter:c});return z.GD(a,d,function(){return this.Eb.Qm(d)})},A5a=function(a,b){z.lt(a,7);var c=new z.ct("",1,a.Ia());b.forEach(function(a){z.jt(c,z.Us(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.yja(c);for(var d=
z.zja(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var k={},l=[],p=0;p<g.length;p++){var r=g[p];k[z.J(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];p=e<b.length-1?b[e+1]:a.Ia().length;z.jt(a,z.Us(g,p,l,Object.keys(k)))}}},B5a=function(a,b,c){b="";a.GGa?a=z.n("Top highlight"):(c=""+z.A(z.kQ(z.C({F6:!0,Qla:!c.useragent.isMobile},a),c)),1==a.Ei&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.y)(c));b+=a;return(0,z.y)(b)},B7=function(a,b){this.mi=a;this.Bsa=b;this.Qe=(this.Rk=b=z.IB(a.node,
b))&&b.getAttribute("name");this.rQ=b?z.Kw(a,b):-1},C7=function(a){var b=a.length;a=a.match(C5a);if(!a)return b;for(var c=0;c<a.length;c++)b+=23-a[c].length;return b},D5a=function(a,b,c){return(0,z.y)(z.iP(z.C({user:c.currentUser,type:"quoteResponses"},a),c))},E5a=function(a,b,c){b="\x3cdiv class\x3d'u-marginLeft10'\x3e\x3cdiv class\x3d\"buttonSet u-inlineBlock\"\x3e"+z.A(z.yk({action:"quote",source:"quote_popover",icon:(0,z.N)(""+z.A(z.Eda())),l:(0,z.N)("button--highlightMenu u-sm-height42 u-sm-lineHeight44 u-accentColor--highlightStrong js-quoteAttributions-pileOn"),
$b:!0,Uj:!0,sS:"quote",wa:!0,isActive:a.isActive},c))+(c.supportsEdit?z.A(z.yk({action:"quote-respond",source:"quote_popover",icon:(0,z.N)(""+z.A(z.Ida())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",$b:!0,wa:!0},c)):"")+(a.hW?z.A(z.yk({action:"twitter",source:"quote_popover",icon:(0,z.N)(""+z.A(z.ik(null))),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",$b:!0,wa:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"'+z.F(z.E("js-quoteAttributions-info u-inlineBlock u-verticalAlignTop u-noWrapWithEllipsis u-maxWidth414 u-paddingTop11 u-paddingRight18 u-paddingBottom0 u-paddingLeft10 u-xs-paddingTop13 u-xs-paddingLeft4 u-xs-maxWidth160"))+
'"\x3e'+B5a(a,0,c)+"\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},D7=function(a){z.Om.call(this);var b=z.Nn();this.lk=b&&new B7(z.Ho(b,!0),a);this.rm=b&&new B7(z.Ho(b,!1),a)},E7=function(a){z.L.call(this);this.aa(a)},F7=function(a,b){var c=new z.Di(z.Lm(b)),c=new z.ie(c.la(z.bCa)),d=new z.ie("https://www.facebook.com/v2.7/dialog/share");z.me(d,z.Ae({app_id:b.facebook.key,href:a.toString(),display:"popup",redirect_uri:c.toString()}));return d},F5a=function(a,b,c){function d(a){return a.replace(/“/g,
"‘").replace(/”/g,"’").replace(/„/g,"‚").replace(/'/g,"’")}b.content=d(b.content);b.name&&(b.name=d(b.name));var e=String(a(b,null,c)),g=C7(e)-280;0<g&&(b.content=z.Dh(b.content,b.content.length-g),e=String(a(b,null,c)));return e},G5a=function(a,b){b=new z.Di(b.authBaseUrl);return new z.ie(b.Al(a))},H5a=function(){var a=z.n("Highlights");return(0,z.y)(""+a)},I5a=function(a,b,c){b=a.post.virtuals.responsesCreatedCount>=c.j.Z7&&(a.post.creator.userId==c.currentUser.userId||(null==a.post.homeCollection?
null:null==a.post.homeCollection.virtuals?null:null==a.post.homeCollection.virtuals.permissions?null:a.post.homeCollection.virtuals.permissions.canManageAll));var d=z.C({Q8:b},a),d=d||{},d=d.Q8;a=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e'+(0,z.y)('\x3cdiv class\x3d"container responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e'+z.A(z.NO({title:(0,z.N)(""+z.A(z.el())),vD:!0,Og:(0,z.N)(""+
(c.supportsEdit&&d?z.xPa(null,c):""))},c))+"\x3c/div\x3e\x3c/div\x3e")+z.vPa(z.C({re:b},a),c)+(b?z.wPa(a,c):"")+z.uPa(c)+"\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(a)},G7=function(a,b,c){z.Q.call(this);this.we=a.get("quotes-data");var d=this.we.vp;d.subscribe("add",this.Pea,this);d.subscribe("remove",this.Pea,this);this.fb=b;this.Vd=b.mm;this.ym=c;this.oba=[];this.Ja=a.get("app");this.Ga=a.get("popover");this.ma=a.get("route-builder");this.u_=a.get("global-event-bus");this.fza=a.get("progressive-media-loader")},
K5a=function(a,b,c,d){var e=J5a(a,b);if(e){var g=a.fb.isPublished(),k=z.Ova(a.fb);e.hW=g&&k;if(c=z.jH(z.HC(z.GC(z.IC(z.oF(z.JC(a.Ga).hb(E5a,e),z.pF),c),{r6:!0,Zu:!0,Ba:!0}),"popover--quoteAttributions"),d).ua())c.jn("deactivate",function(){this.Gp===b&&H7(this,null)},a),c.mo().ba("quote",a.yta.bind(a,c)).ba("quote-respond",a.zta.bind(a,c)).ba("twitter",a.Ata.bind(a))}},J5a=function(a,b){if("anon"==b.nb())return{isActive:!1,GGa:!0};var c=I7(a,b),d=b.Dd();b=b.Ae();a=v5a(a.we,c,d,b);if(!a||!a.length)return null;
a=(0,z.Ib)(a,function(a){return a.user});c=(0,z.vd)(a,function(a){return a.userId!=z.mq().userId});return{isActive:(0,z.cd)(a,function(a){return a.userId==z.mq().userId}),social:c,Ei:a.length}},L5a=function(a,b){a=a.Vd.querySelectorAll('.markup--quote[name~\x3d"'+b.Xi()+'"]');return z.Za(a)},I7=function(a,b){b=b.gc()[0].name;return(b=z.Fs(a.Vd,b))?a.fb.Wi(b):null},M5a=function(a,b){var c=z.On(b);return(c=z.RE(a.ym,c))?u5a(a.we,b,c):null},H7=function(a,b){a.Gp!==b&&(a.Gp&&N5a(a,a.Gp,!1),b&&N5a(a,b,
!0),a.Gp=b)},N5a=function(a,b,c){L5a(a,b).map(function(a){z.yd(a,"is-targeted",c)})},J7=function(a,b){(b=O5a(a,b))&&z.PE(a.Ak(),b)},O5a=function(a,b){var c=b.gc(),d=z.Fs(a.Vd,c[0].getName());a=z.Fs(a.Vd,z.Ra(c).getName());return z.kN(d,b.Dd(),a,b.Ae())},K7=function(a,b,c,d){a={postId:a.fb.Na(),quoteId:b,source:d};z.Hx(c?z.wva:z.CEa,a)},P5a=function(a,b){z.MB(a,z.LB,z.Zb(b,z.Wb(!0)),void 0)},Q5a=function(a,b,c){z.qa(a)||(a=a.toString());var d=window,e={scrollbars:!0,sJa:!0,toolbar:!1,location:!0,width:670,
height:690};z.Db(e,c||{});e.left||e.top||(e.width=(0,window.parseInt)(e.width,10),e.height=(0,window.parseInt)(e.height,10),e.left=Math.max(d.screenX+Math.round(d.outerWidth/2-e.width/2),0),e.top=Math.max(d.screenY+Math.round(d.outerHeight/2-e.height/2),0));var g={scrollbars:"scrollbars",sJa:"resizable",toolbar:"toolbar",location:"location",width:"width",height:"height",left:"left",top:"top"};c=z.Mha(e,function(a,b,c){g[c]&&("boolean"==typeof b&&(b=b?"yes":"no"),a.push(g[c]+"\x3d"+b));return a},[]).join();
return d.open(a,b,c)},R5a=function(a){var b=z.kw(z.qxa,{AHa:!0});b&&(b=b.split(/\s+/),b=b.filter(function(a){return!z.Fa(a)}),b.length&&z.ud(a,b))},S5a=function(a){return(0,z.y)(z.A(z.dl(String(a.content)))+" — "+z.A(z.ts(a))+" "+z.A(a.url))},T5a=function(a,b,c){return(0,z.Ai)("https://"+z.kh(c.textshotHost)+"/image")},U5a=function(a,b,c){return(0,z.Ai)("https://twitter.com/"+z.kh(c.currentUser.twitterScreenName)+"/status/"+z.kh(a.id))},V5a=function(){var a=z.y,b;b=z.n("Failed to load image");b=(0,z.y)(""+
b);return a('\x3cspan class\x3d"tweetEditor-imageStatusIcon"\x3e\x26times;\x3c/span\x3e'+z.A(b))},W5a=function(a,b,c){b=z.y;a='\x3cdiv class\x3d"tweetEditor u-sizeFullWidth"\x3e\x3cdiv class\x3d"js-tweetEditor-error tweetEditor-error u-paddingBottom10 u-textAlignCenter u-textColorRed"\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-avatar"\x3e'+z.A(z.Al({user:a.user,tf:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-tweetContainer"\x3e\x3cdiv class\x3d"tweetEditor-textContainer"\x3e\x3cdiv class\x3d"js-tweetEditor-text textInput textInput--chromeless u-textAlignLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-textshot"\x3e\x3cdiv class\x3d"js-tweetEditor-imageStatus tweetEditor-imageStatus"\x3e';
var d;d=z.n("Loading image attachment…");d=(0,z.y)(""+d);a=a+z.A(d)+"\x3c/div\x3e";d={};d=(0,z.y)(z.Ej(z.C({name:"addCircled",size:"21px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"21" height\x3d"21" viewBox\x3d"0 0 21 21" \x3e\x3cpath d\x3d"M2.286 12.691a8.358 8.358 0 0 0 2.192 3.831A8.298 8.298 0 0 0 8.3 18.715c.73.19 1.462.288 2.192.29a8.363 8.363 0 0 0 2.2-.29 8.286 8.286 0 0 0 3.822-2.193 8.264 8.264 0 0 0 2.201-3.82c.19-.732.285-1.462.285-2.193a8.248 8.248 0 0 0-.285-2.2 8.265 8.265 0 0 0-2.2-3.823 8.258 8.258 0 0 0-3.822-2.2A8.66 8.66 0 0 0 10.5 2a8.188 8.188 0 0 0-2.192.286 8.33 8.33 0 0 0-3.831 2.2 8.298 8.298 0 0 0-2.193 3.822A8.66 8.66 0 0 0 2 10.5c0 .731.095 1.461.286 2.191zm1.557-.413a6.74 6.74 0 0 1-.239-1.773c0-.592.08-1.184.24-1.773a6.77 6.77 0 0 1 1.786-3.09 6.73 6.73 0 0 1 3.085-1.79c.59-.16 1.181-.24 1.777-.24.596 0 1.188.08 1.777.24a6.736 6.736 0 0 1 3.094 1.786 6.801 6.801 0 0 1 1.787 3.094c.16.59.239 1.178.239 1.768 0 .59-.08 1.182-.24 1.778a6.75 6.75 0 0 1-1.786 3.093 6.801 6.801 0 0 1-3.094 1.787 6.707 6.707 0 0 1-3.545 0A6.74 6.74 0 0 1 5.63 15.37a6.746 6.746 0 0 1-1.787-3.093zm2.937-2.055c0-.134.049-.25.148-.345a.494.494 0 0 1 .359-.143H9.23a.478.478 0 0 0 .35-.148.475.475 0 0 0 .147-.35V7.303c0-.141.048-.262.144-.363a.458.458 0 0 1 .345-.152h.562c.134 0 .25.05.35.152a.502.502 0 0 1 .147.363v1.934c0 .135.048.252.143.35a.46.46 0 0 0 .345.148h1.945c.14 0 .26.048.358.143.099.096.148.21.148.345v.562a.476.476 0 0 1-.148.35.486.486 0 0 1-.358.147h-1.945a.472.472 0 0 0-.345.143.47.47 0 0 0-.143.345v1.944c0 .14-.05.262-.148.36a.478.478 0 0 1-.35.147h-.56a.498.498 0 0 1-.489-.507V11.77a.461.461 0 0 0-.148-.345.487.487 0 0 0-.35-.143H7.287a.488.488 0 0 1-.36-.147.476.476 0 0 1-.147-.35v-.562z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
d)));d=(0,z.N)(""+z.A(d));var e;e=z.n("Include quote image");e=(0,z.y)(""+e);a=a+z.A(z.yk({icon:d,isPrimary:!0,wa:!0,l:"js-tweetEditor-addTextshot u-hide",action:"add-textshot",text:(0,z.N)(""+z.A(e))},c))+'\x3cdiv class\x3d"js-tweetEditor-imageContainer tweetEditor-imageContainer"\x3e';d=(0,z.N)("\x26times;");e=z.n("Remove quote image from tweet");e=(0,z.y)(""+e);return b(a+z.A(z.wk({s:d,Yc:!0,l:"js-tweetEditor-removeTextshot tweetEditor-removeTextshot",title:(0,z.N)(""+z.A(e)),action:"remove-textshot"},
c))+'\x3cimg class\x3d"js-tweetEditor-image tweetEditor-image" data-action\x3d"toggle-expand-image"\x3e\x3c/img\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+(c.variants.textshots_userid?'\x3cdiv class\x3d"u-textColorRed"\x3eTweet to test account @fuzzyoctopusfee\x3c/div\x3e':""))},X5a=function(){var a=z.n("An error occurred, and the tweet wasn’t posted to Twitter.");return(0,z.y)(""+a)},Y5a=function(a,b,c){var d="";b=z.n("Tweet posted.");a=a.DKa;var e;e=z.n("View the tweet");e=(0,z.y)(""+
e);d+=b+" "+z.A(z.O({vb:!0,href:a,s:(0,z.N)(""+e)},c));return(0,z.y)(d)},Z5a=function(a,b,c){a=z.n("Tweet must be {$twitterMaxTweetLength} characters or less.",{twitterMaxTweetLength:z.A(c.j.EKa)});return(0,z.y)(""+a)},$5a=function(a){if(!a)return"";var b=[],c=z.zb(["grafId","noteId","command","startIndex","endIndex"]),d;for(d in a)b[c[d]]=a[d];return b.join("-")},L7=function(a){z.ix.call(this);this.yc=a.get("dom-model-converter");this.Jda={};this.Bca={};this.r1={};this.qa=a;this.ol=a.get("request");
this.ma=a.get("route-builder");this.Aa=a.get("model-store");this.ob="";this.lea=z.km;this.lba=!1;this.Gh=null},M7=function(a,b){var c=a.Jda[b];c||(c=a.Jda[b]=new z.dD,a.za("new_note_list",c,a));return c},a6a=function(a,b){if(!b)return!1;var c=b.Ia();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.Ja(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,a.endIndex=b.index+c,a.content=b[0],!0):!1},N7=function(a,b,c){var d=
b.Na(),e=b.vg(),g=M7(a,b.ie()),k=g?g.indexOf(b):-1,l=b.ny();b.Qs(c);"HIDDEN"==c?a.Aa.remove(b):b=z.EC(a.Aa,b);var p=g?g.indexOf(b):-1;return{Gl:a.ol.put(a.ma.la(z.kCa,{postId:d,noteId:e}),{state:c}),EL:function(){b.Qs(l);-1==p&&(-1==k?g.add(b):z.fD(g,b,k))}}},O7=function(a,b,c,d,e,g){var k=z.J(a.Up(c,e),"replies"),l=z.Sa(k,function(a){return a.ly()==b}),p=k[l];"HIDDEN"==g&&z.Wa(k,l);c=a.ma.la(z.nCa,{postId:d,noteId:c,replyId:b});a=a.ol.put(c,{state:g});var r=z.Sa(k,function(a){return a.ly()==b});
return{Gl:a,EL:function(){-1==r&&z.db(k,l,0,p)}}},b6a=function(a,b,c){this.range=a;this.anchor=b;this.jC=b.getAttribute("name");this.highlight=c},P7=function(a,b,c){z.Q.call(this);this.Wza=b;this.Rya=c;this.Oa=a.get("screen");this.ib=a.get("screen-request")},Q7=function(a,b,c,d){z.Q.call(this);this.Oa=a.get("screen");this.sp=c;this.lh=d;this.RP=!1;this.fw=this.gh=null;this.Wa(b)},R7=function(){},c6a=function(a){this.qQ=a},S7=function(a,b){return b?z.Fs(a.qQ,b):null},d6a=function(a,b,c){P5a(a.qQ,function(a){var e=
a.getAttribute("name");e&&b.call(c,a,e)})},e6a=function(a,b){return z.vg(a.qQ,b)?a.qQ:null},T7=function(a,b,c,d,e){z.dW.call(this,a,b);this.bb(new z.wV(c));this.bb(new z.rW(!1));this.bb(new z.uW(a));this.bb(new z.eW);this.bb(new z.xW(a,!1,!1));this.bb(new z.zW(d,!0));this.jl=!0;this.xm=d;this.ol=a.get("request");this.Fa=a.get("dialog");this.W0=e;this.ua()},f6a=function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.y)(""+
a)},g6a=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");return(0,z.y)(""+a)},h6a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.y)(""+a)},i6a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");return(0,z.y)(""+a)},j6a=function(){var a=z.n("The note has been dismissed.");return(0,z.y)(""+a)},k6a=function(){var a=z.n("The note has been deleted.");return(0,z.y)(""+a)},l6a=function(){var a=
z.n("The reply has been deleted.");return(0,z.y)(""+a)},m6a=function(){var a=z.n("Write a note…");return(0,z.y)(""+a)},n6a=function(){var a=z.n("Cancel");return(0,z.y)(""+a)},U7=function(a,b,c,d,e){T7.call(this,a,b,e||"Leave a note",400,d||null);this.ob=c;this.ma=a.get("route-builder");this.yf=a.get("notes-data")},V7=function(a,b,c,d,e,g){T7.call(this,a,b,"Leave a reply…",200,d);this.ma=a.get("route-builder");this.yf=a.get("notes-data");this.ob=c;this.Lea=g||null;this.Qe=e},p6a=function(a,b,c){var d=
'\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||a.p9;b=a.notes.length||a.fW;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.A(z.jz({title:(0,z.N)(z.A(H5a())+" ("+z.A(a.quotes.length)+")"),Vf:!0},c)),k;k={Xka:a.quotes,$Ka:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';if(!k.$Ka)var p=z.n("Learn more"),l=l+z.A(z.jz({title:(0,z.N)(""+z.A(H5a())),Vf:!0,Og:(0,z.N)(""+z.A(z.iz({href:(0,z.M)(""+z.G((0,z.Ai)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),
moreText:(0,z.N)(""+p),zb:!0},c)))},c));for(var p="list u-marginTop5 u-marginBottom15"+(k.Xka.length?"":" u-hide"),p=(0,z.N)(p),l=l+('\x3cul class\x3d"'+z.F(p)+'"\x3e'),p=k.Xka,r=p.length,u=0;u<r;u++){for(var w=p[u],D="",H=w.quotes,P=H.length,R=0;R<P;R++)D+=""+H[R].quoteId+(R!=P-1?",":"");D=z.E(D);l+='\x3cli class\x3d"list-item list-item--inline u-border0" data-quote-ids\x3d"'+z.F(D)+'" data-quote-creator-id\x3d"'+z.F(w.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+
z.A(z.yl(z.C({user:w.user,Fe:!0},k),c))+"\x3c/li\x3e"}k=(0,z.y)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.A(k)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.p9?" is-withEditor":"")+'"\x3e'+z.A(z.jz({title:(0,z.N)(""+z.A(z.el())),Vf:!0},c)),a.p9&&c.supportsEdit&&c.isAuthenticated?(k={},k=(0,z.y)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses"\x3e'+z.iP(z.C({user:c.currentUser,isCollapsed:!0,sD:!0,type:"quoteResponses",ov:(0,z.N)(""+
z.A(z.ufa()))},k),c)+"\x3c/div\x3e"),k=z.A(k)):k="",g=g+k+o6a(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.FIa&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';e=b="";k=a.post.homeCollection;k=a.post.creator.userId!=c.currentUser.userId?k?z.n("Private notes are visible to you, the author, and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you, the author, and the editors of any publication this story is added to."):
k?z.n("Private notes are visible to you and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you and the editors of any publication this story is added to.");e+=k;e=(0,z.y)(e);e=""+z.A(e);e=(0,z.N)(e);b+='\x3cspan data-tooltip\x3d"'+z.F(e)+'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.y)(z.Ej(z.C({name:"lock",size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
g)));g=(0,z.N)(""+z.A(g));e=z.n("Private notes");e=(0,z.y)(""+e);b={xKa:g,title:(0,z.N)(""+z.A(e)),Vf:!0,Og:(0,z.N)(b),l:"heading--privateNotes"};b=(0,z.y)(z.gz(z.C({vk:(0,z.N)(""+z.hz(b,c)),uHa:!0},b)));b=d+=z.A(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.fW?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(k=0;k<e;k++)d+=W7({note:g[k],post:a.post,kM:a.kM},0,c);a.fW?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.A(g.name)}),a+=g,a=(0,z.y)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.A(z.xk({action:"show-note-editor",text:(0,z.N)(""+z.A(a)),l:"privateNotes-prompt"},0,c)),g=z.y,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.A(z.zl({user:c.currentUser,tf:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',k=z.n("Send"),k=(0,z.y)(""+k),c=g(e+z.A(z.xk({action:"save-note",isPrimary:!0,l:"js-saveNoteButton",
text:(0,z.N)(""+z.A(k))},0,c))+z.A(z.xk({action:"hide-note-editor",text:(0,z.N)(""+z.A(n6a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.y)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.qE&&(a=z.n("Show next tip"),b=z.n("Show previous tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.A(z.yk({Fb:!0,Yc:!0,wa:!0,action:"previous-highlight-tip",icon:(0,z.N)(""+z.A(z.uda())),title:(0,z.N)(""+b)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.A(z.yk({Fb:!0,Yc:!0,wa:!0,action:"next-highlight-tip",icon:(0,z.N)(""+z.A(z.vda())),title:(0,z.N)(""+a)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(d+"\x3c/div\x3e")},o6a=function(a,b,c){return(0,z.y)(z.A(z.AQ({posts:a.responses,source:"quoteResponses",
lU:!0},0,c)))},W7=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,k=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=k||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var p=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?" js-reply-"+a.note.replyId:"")),p=z.E(p),p='\x3cdiv class\x3d"privateNotes-item '+
z.F(p)+' js-note" data-note-id\x3d"'+z.F(a.note.noteId)+'"\x3e'+(g?z.A(z.yl({user:a.note.author},c)):z.A(z.jO({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.A(z.Pk({user:a.note.author},c));g||!(k||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.sja?k="":(k=z.n("(Editor)"),k=(0,z.y)(""+k),k='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+z.A(k)+"\x3c/span\x3e");p=
p+k+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.A(z.Ah(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';k=z.A(z.fu(String(a.note.content),c));l=String(k).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");k=z.Ig(k,z.Kg)?(0,z.y)(l,z.fca(k)):l;d=""+(p+k+"\x3c/div\x3e"+(d?q6a({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';if(e)for(e=a.note.replies,
g=e.length,p=0;p<g;p++)k=e[p],d+=W7({note:k,post:a.post,sja:a.note.author.userId==k.author.userId},0,c);e=d;a.kM?(g=z.y,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.A(z.IQ({user:c.currentUser,tf:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',p=z.n("Send"),p=(0,z.y)(""+p),g=g(d+z.A(z.xk({action:"save-reply",isPrimary:!0,text:(0,z.N)(""+z.A(p))},0,c))+z.A(z.xk({action:"hide-reply-editor",text:(0,z.N)(""+z.A(n6a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e")):
g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.kM?(d=z.y,p=z.n("Reply"),p=(0,z.y)(""+p),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.A(z.xk({isPrimary:!0,action:"show-reply-editor",l:"privateNotes-prompt",text:(0,z.N)(""+z.A(p))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+q6a({note:a.note,isPrimary:!0,$ia:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.y)(d+"\x3c/div\x3e")},q6a=
function(a,b){var c=z.y,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.$ia?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.$ia?z.n("Dismiss note"):z.n("Delete");a=(0,z.y)(""+a);a=z.A(a);return c(z.A(z.xk({actionValue:d,action:e,l:"privateNotes-delete js-deleteNote",text:(0,z.N)(""+a)},0,b)))},r6a=function(a,b,c){b="";if(0==a.e9)a=1==a.qE?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.A(a.qE)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.nh(z.sj({imageId:"1*SyXCciYXeNpx4-GUAuh0XQ.gif"},0,c)))+'"\x3e';else if(1==a.e9)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.nh(z.sj({imageId:"1*dEp02HXMKtAeKxsV5MWqGg.gif"},0,c)))+'"\x3e';else if(2==a.e9){a=z.n("so that you can save your highlights and share them with others.");
var d=z.n("Sign up and create a profile");b+=z.A(z.xk({text:(0,z.N)(""+d),$b:!0,source:(0,z.N)(""+z.A(z.Ci({name:c.j.kd.Ena,susiEntry:c.j.Ha.dF}))),l:"u-textUnderline"},0,c))+" "+a}return(0,z.y)(b)},X7=function(a,b,c,d,e,g,k,l){z.Q.call(this);this.qa=a;this.ya=a.get("butter-bar");this.fb=b;this.Qe=c;this.fk=e;this.we=a.get("quotes-data");this.yf=a.get("notes-data");this.zj=a.get("responses-data");this.mf=g;this.W0=d;this.T1=(this.yI=k)?k.Xi():null;this.Pf=this.Ic=null;this.hk={};this.Nca=!!z.nq();
this.Oca=!!z.Oq();this.hB=this.Nca&&this.Oca&&z.hF(b);this.$q=null;this.zP=0;this.Sfa=w5a(this.we,this.Qe);this.Iw=l;this.Wa(this.Sq());this.Nda=z.nq()?2:3},s6a=function(a){a.sb(".js-block").forEach(function(a){this.Ta(a,"mouseenter",this.$ta,this);this.Ta(a,"mouseleave",this.q3,this)},a)},t6a=function(a){a.sb(".js-note").forEach(function(a){this.Ta(a,"mouseenter",this.Yta,this);this.Ta(a,"mouseleave",this.q3,this)},a)},u6a=function(a,b){var c=a.query(".js-note-"+b);a.hk[b]||(a.hk[b]=new V7(a.qa,
c.querySelector(".js-replyEditor"),a.fb.Na(),b,a.Qe),z.kx(a,a.hk[b],"saving",a.wxa,a),z.kx(a,a.hk[b],"save",a.rxa,a),z.kx(a,a.hk[b],"fail",a.pwa,a));z.td(c,"is-noteEditorVisible");a.hk[b].focus()},v6a=function(a,b){var c=a.hk[b];c&&(c.eb()&&c.hd(""),a=a.query(".js-note-"+b),z.wd(a,"is-noteEditorVisible"))},w6a=function(a,b,c){var d=S7(a.mf,a.Qe);if(d){var e=[];a.Iw&&(e=a.Iw.quotes.map(function(a){return a.Xi()}));(0,z.Ib)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),
d=z.Va(d,b);if(this.Iw)var l=a.getAttribute("name").split(" "),d=d&&(0,z.cd)(l,z.Va.bind(null,e));z.yd(a,"is-selected",c&&d)},a)}},Y7=function(a){return(a=z.Cs(a,function(a){return z.sd(a,"js-note-item")}))&&a.getAttribute("data-note-id")},x6a=function(a,b,c,d){b=new z.VE(b,300);b.Wa(c);b.subscribe("dismiss",d,a);b.ua();return b},Z7=function(a){var b=a.gc(),c=a.Dd();a=a.Ae();1<b.length&&(a=b[0].Ia().length);var d=new z.ns;d.rq(b[0].getName());d.Eg(c);z.K(d,"endIndex",a);d.hd(b[0].Ia().substring(c,
a));return d},$7=function(a,b){b%=a.Nda;0>b&&(b=a.Nda-1);a.zP=b;(b=a.query(".js-highlightTip"))&&z.jw(b,r6a,{e9:a.zP,qE:a.Sfa})},a8=function(a,b,c,d){z.Q.call(this);this.Wa(this.Sq(d));this.Db=a.get("dom-monitor");this.fb=b;this.Tca=!b.Za().Wr()||b.Ob();this.ob=b.Na();this.mf=c;this.we=a.get("quotes-data");this.zj=a.get("responses-data");this.yf=a.get("notes-data");this.pw=null;this.Kh={}},y6a=function(a,b){b.forEach(function(a){a&&b8(this,a)},a)},b8=function(a,b){if(!a.pw)if(S7(a.mf,b)){var c=z6a(a,
b),c=A6a(a,c),c=B6a(a,c),c=C6a(a,c);a.Kh[b]=c;D6a(a,b)}else delete a.Kh[b]},E6a=function(a,b){if(!a.pw){var c=a.Kh[b];if(c){var d=c.length,c=B6a(a,c),c=C6a(a,c);a.Kh[b]=c;d!=c.length?D6a(a,b):c.forEach(function(a){a.Xa&&a.offsetTop&&(a.Xa.style.top=a.offsetTop+"px")})}}},F6a=function(a,b,c){return z.Ta(a.Kh[b]||[],function(a){return a.Xa==c})},z6a=function(a,b){var c=[];M7(a.yf,b).Rg(function(a){var e=a.KC(),g;e?(g=this.yf.xT(e),e=g.lb(),g=z.J(g,"endIndex")):(e=0,g=a.eb().length);c.push({anchor:b,
startIndex:e,endIndex:g,notes:[a],quotes:[],responses:[]})},a);if(a.Tca)return c;(a.we.$t[b]||[]).forEach(function(a){var e=G6a(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);A7(a.zj,b).forEach(function(a){var e=y7(a);e&&(e=z7(e)&&z7(e).lo())&&(e=G6a(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},A6a=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});
b.forEach(function(a){var b=z.Sa(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.YH(c[b],a):c.push(a)},a);return c},C6a=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Sa(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.YH(c[b],a):c.push(a)}},a);return c},D6a=function(a,b){a.sb(".js-paragraphControl-"+b).forEach(z.og);a.Kh[b]=a.Kh[b].map(function(a){var b=H6a(this,a),b=z.lw(I6a,b);b.style.top=a.offsetTop+"px";a.Xa=
b;this.oa().appendChild(a.Xa);z.td(b,"is-visible");return a},a)},H6a=function(a,b){var c=b.notes,d=b.responses,e=u7(a.we,b.quotes),g=d?d.length:0,k=c?c.length:0,l=0,p=0,r=0,u=!1,w=!1,D={},H={},P=z.mq().userId,R=a.fb.Za().Bf().nb();c.forEach(function(a){var b=a.eK();b&&((a=z.J(a,"replies"))&&a.forEach(function(a){k++;a.author&&(a.author.userId==P&&l++,a.author.social&&a.author.social.isFollowing&&(D[a.author.userId]=a.author),H[a.author.userId]=!0)}),H[b.userId]=!0,b.userId==P&&l++,b.userId==R?p++:
r++,b.social&&b.social.isFollowing&&(D[b.userId]=b))});e.forEach(function(a){a=a.user;H[a.userId]=!0;a.userId==P&&(u=!0);a.social&&a.social.isFollowing&&(D[a.userId]=a)});d.forEach(function(a){a=a.Bf();H[a.userId]=!0;a.userId==P&&(w=!0);a.social&&a.social.isFollowing&&(D[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.nb()});return{postId:a.ob,jC:b.anchor,DIa:k,tJa:g,Yy:w,Py:l,qka:p,EIa:r,n1a:e.length,Xy:u,Qia:Object.keys(H).length,xGa:z.rb(D),qE:c.length}},G6a=function(a){var b=a.Dd(),
c=a.Ae();1<a.paragraphs.length&&(c=a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},B6a=function(a,b){var c=z.Gw();return b.map(function(a){var b=this.mf.get(a.anchor),g=this.fb.Wi(b);if(!g)return a;var k;4==g.type&&(g.Ia()&&(k=b.querySelector("figcaption")),k||(k=b));if(!k){g=a.startIndex+1;b=[b];k=0;for(var l=null;0<b.length&&k<g;)if(l=b.pop(),!(l.nodeName in z.UJa))if(3==l.nodeType){var p=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");k+=p.length}else if(l.nodeName in z.hR)k+=
z.hR[l.nodeName].length;else for(p=l.childNodes.length-1;0<=p;p--)b.push(l.childNodes[p]);k=l}g=z.Jw(k,!0);a.offsetTop=Math.round(g.top+c.top);return a},a)},I6a=function(a,b,c){b=z.y;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.F(a.jC)+' u-noUserSelect"\x3e',e=z.y,g;if(a.DIa||a.tJa){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.F(a.jC)+'"\x3e';var k;k={};k=(0,z.y)(z.Ej(z.C({name:"asteriskFilled",
size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
k)));g=g+z.A(k)+"\x3c/div\x3e"}else g="";var l=k="",p="",r=1==a.Py?z.n("a note"):z.n("notes"),p=p+(""+r),p=z.E(p);1==a.Qia&&(0<a.Py||a.Xy||a.Yy)&&(0<a.Py&&a.Xy&&a.Yy?(p=z.n("highlighted, responded, and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Py&&a.Yy?(p=z.n("responded and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Py&&a.Xy?(p=z.n("highlighted and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.Xy&&a.Yy?(p=z.n("highlighted and responded"),l+=" "+p):a.Xy?
(p=z.n("highlighted"),l+=" "+p):0<a.Py?(p=z.n("left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.Yy&&(p=z.n("responded"),l+=" "+p));l=z.E(l);k+='\x3cspan class\x3d"paragraphControls-itemText"\x3e';p="";if(0<a.qka&&0==a.EIa&&!a.Xy&&!a.Yy)c=1==a.qka?z.n("Note to self"):z.n("Notes to self"),p+=c;else{r="";if(0<a.qE)var u=z.n("Top highlight"),r=r+u;p+=z.A(z.kQ(z.C({social:a.xGa,isActive:0<a.Py||a.Xy||a.Yy,Ei:a.Qia,F6:!0,QIa:!0,pha:(0,z.N)(r)},a),c));p+=z.A(l)}p=(0,z.N)(p);k+=z.A(z.oIa(z.C({text:p},
a)))+"\x3c/span\x3e";a=(0,z.y)(k);a=e(g+a);return b(d+a+"\x3c/div\x3e")},c8=function(a,b,c){z.Q.call(this);this.qa=a;this.Ja=a.get("app");this.Fsa=a.get("floating-components");this.Oa=a.get("screen");this.rb=a.get("screen-service");this.Db=a.get("dom-monitor");this.fb=b;this.Vd=b.Vd;this.mm=this.Vd.querySelector(".js-postField");this.eea=this.Oa.oa().querySelector(".js-notesPositionContainer");this.we=a.get("quotes-data");this.yf=a.get("notes-data");this.yf.subscribe("new_note_list",this.Nwa,this);
this.zj=a.get("responses-data");this.lm=null;this.mf=new c6a(this.Vd.querySelector(".js-notesSource"));this.VH=this.Kh=this.iR=null;this.Kh=new a8(a,b,this.mf,this.eea);this.track(this.Kh);this.VH=this.Kh.oa();this.gh=this.A0=null;this.Se=c},e8=function(a,b){if(a.isActive()){var c=(b=b||a.A0)&&b.dU,d=b&&b.noteId;c&&(a.ix(c),d&&a.yf.Up(d,c)&&a.gh&&z.t(a.gh,function(){return d8(a,c,null,d)}));z.Rna(a.Ja,"")}else a.A0=b||null},d8=function(a,b,c,d,e,g){var k={Gk:!0,y6:z.pw()};a.c2();c=new X7(a.qa,a.fb,
b,d||"",c||null,a.mf,e||null,g||null);c.subscribe("set-active-highlight",a.afa,a);c.subscribe("reset-highlight",a.dAa,a);c.subscribe("close",a.c2,a);b=g&&g.Xa?g.Xa:a.mf.get(b);g=z.Txa(a.Fsa);g.Qn=b;b=g.uE(c);b.pJ=k;k=b.LW(a.Kn.bind(a));k.cR=!0;a.lm=k.ua()},J6a=function(a,b,c){var d=a.fb.Wi(S7(a.mf,b));if(d&&4!=d.type){z.lt(d,4);if(c){if(!a6a(c,d))return;z.jt(d,z.Ts(c.startIndex,c.endIndex,c.id))}c=a.fb.Ob();var e=a.fb.Za();c={mode:c?"edit":"view",Pj:z.yt(e),media:null,Zl:null,sections:!0,Hk:!1,Fk:!1,
Cl:!1,Rf:!1,postId:e.id};a.mf.get(b).innerHTML=z.Vt(d,z.Mm,c)}},K6a=function(a,b){var c=z.Nn();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=c.Uf();var d=e6a(a.mf,b);if(!d)return null;a=(b=z.Cs(b,z.LB,d))&&a.fb.Wi(b);if(!b)return null;var d=z.Lw(c,b,!0),e=z.Lw(c,b,!1);return-1==d||-1==e?null:new b6a(c,b,new z.ns({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.Ia().substring(d,e)}))},L6a=function(){},f8=function(a,b){z.Q.call(this);this.Oh=b||I5a;this.ib=a.get("screen-request");
this.va=null;this.A3=a.get("screen-view-state");this.qa=a;this.nfa=this.I2=!1;this.o1=this.Ic=null},g8=function(a){z.ix.call(this);this.uz=a},M6a=function(a,b,c){a=z.qa(a)?new z.ie(a):a;(a=Q5a(a,b,c||{}))&&(new g8(a)).focus()},N6a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder")},h8=function(a){z.Om.call(this);this.qa=a;this.wG=a.get("dialog");this.pa=a.get("request");this.ma=a.get("route-builder");this.ya=a.get("butter-bar");this.wJ=this.Fa=this.zx=this.va=null;this.EP=!1},P6a=
function(a){var b=a.Fa.query(".js-tweetEditor-image"),c=a.Fa.query(".js-tweetEditor-imageContainer"),d=a.Fa.query(".js-tweetEditor-imageStatus");z.td(c,"u-hide");var e=O6a(a);e.base64=!0;z.v(z.t(a.pa.post(z.kw(T5a),e,{kC:!1,withCredentials:!1}),function(a){b.src="data:image/png;base64,"+a;z.wd(c,"u-hide");z.td(d,"u-hide");this.EP=!0},a),function(a){z.ex(a);z.jw(d,V5a)},a)},Q6a=function(a,b){return 280>=C7(b)?!0:(b=a.Fa.query(".js-tweetEditor-text"),(new z.zA(b,{name:"shimmy-shake",duration:400})).start(),
a=a.Fa.query(".js-tweetEditor-error"),z.jw(a,Z5a),!1)},O6a=function(a){var b=a.va,c=a.zx.uKa;a=a.zx.tKa;var d=b.creator,e=b.approvedHomeCollection,g=z.Mm,k=null;e&&(k=e.image);var l=null;e&&e.logo&&e.logo.imageId&&(l=e.logo.imageId);var p=null;e&&e.tintColor&&2==e.colorBehavior&&e.logo&&e.logo.imageId&&(p=e.tintColor);var r=null;e&&e.tintColor&&(r=z.MJa(e.tintColor),r=z.$r(r,.6).color);return new E7({content:c,altText:a,title:b.title,author:d&&d.name,date:z.zh(b.createdAt,g),authorAvatarId:d&&d.imageId,
collection:e&&e.name,collectionAvatarId:k?k.imageId:null,collectionLogoId:l,collectionBackgroundColor:p,collectionHighlightColor:r,version:2})},R6a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder");this.qa=a};z.q(s7,z.L);z.f=s7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return"Placement"};z.f.uf=function(){return z.J(this,"items")};z.f.Lc=z.h(381);z.f.bM=function(a){return z.K(this,"location",a)};z.f.Cd=z.h(424);z.f.Wb=function(a){return z.K(this,"index",a)};
z.f.ha=function(){return s7.prototype};z.f.fa={name:"Placement",ia:!1,fields:{items:{name:"items",g:function(){return z.pM},ra:z.U,h:1},location:{name:"location",g:function(){return z.gBa},h:2},index:{name:"index",g:z.W,h:3}},ka:{}};z.f.Cd=z.Y(424,function(){return z.J(this,"index")});z.f.Lc=z.Y(381,function(a){return z.K(this,"items",a)});z.m(v7,z.Oe);v7.prototype.zk=function(a){var b={};z.ED(this,b,a.Pb(),"");return b};
v7.prototype.Jb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[[\]]+/).filter(function(a){return!!a}),g=c,k=e.shift();k;){var l=z.Vh(g,k);if(!l)break;var p=l.g();if(l.ra()){var r=z.Oh(g,k)||[],u=e.shift(),w=Number(u);if(void 0===u||!Number.isInteger(w)||0>w)break;if(p.prototype instanceof z.Gh)l=r[w],l||(l=new p,r[w]=l),z.K(g,k,r),g=l;else{if(void 0!==e.shift())break;p=p5a(b[a],l);r[w]=p;z.K(g,k,r)}}else if(p.prototype instanceof z.Gh)r=z.Oh(g,
k),r||(r=new p,z.K(g,k,r)),g=r;else{if(void 0!==e.shift())break;p=p5a(b[a],l);z.K(g,k,p)}k=e.shift()}});return c};z.q(w7,z.Xh);z.f=w7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.QT=z.h(566);z.f.ha=function(){return w7.prototype};z.f.fa={name:"PlacementsResponse",ia:!1,fields:{placements:{name:"placements",g:function(){return s7},ra:z.U,h:1}},ka:{}};z.q(x7,z.L);x7.prototype.ca=function(){return""};x7.prototype.ea=function(){return""};x7.prototype.ha=function(){return x7.prototype};
x7.prototype.fa={name:"PlacementsRequestQuery",ia:!1,fields:{requestContext:{name:"requestContext",g:function(){return z.br},h:1},slots:{name:"slots",g:function(){return z.dr},ra:z.U,h:2}},ka:{}};z.dW.prototype.$V=z.Y(581,function(a){a!=this.TP&&this.Ab&&(this.Ab.ei.contentEditable=a);this.TP=a});z.dH.prototype.LW=z.Y(572,function(a){this.Kn=a;return this});z.iH.prototype.LW=z.Y(571,function(a){this.Kn=a;return this});
z.$F.prototype.z5=z.Y(570,function(a){a=y7(a);if(!a)return null;a=z7(a)&&z7(a).lo();return a?(a=a.gc())&&a.length?a[0].getName():null:null});w7.prototype.QT=z.Y(566,function(){return z.J(this,"placements")});z.FD.prototype.QT=z.Y(565,function(a,b){var c=this;a=r5a(s5a(new x7,a),b);a=(new v7).zk(a);var d=this.ma.la(z.mza,{},a);return z.GD(this,d,function(){return z.t(c.pa.get(d,{background:!0}),function(a){a=c.Ka.jc(w7,a);c.Aa.pc(a);return a})})});
z.Cx.prototype.Up=z.Y(482,function(){return z.J(this,"note")});z.zD.prototype.Up=z.Y(481,function(a){return this.nc("Note",a)});z.ms.prototype.ly=z.Y(452,function(){return z.J(this,"replyId")});z.Cx.prototype.ly=z.Y(451,function(){return z.J(this,"replyId")});z.ks.prototype.dz=z.Y(450,function(a){return z.K(this,"highlight",a)});z.ks.prototype.xT=z.Y(449,function(){return z.J(this,"highlight")});z.ks.prototype.sv=z.Y(448,function(a){return z.K(this,"author",a)});
z.ms.prototype.sv=z.Y(447,function(a){return z.K(this,"author",a)});z.ks.prototype.eK=z.Y(446,function(){return z.J(this,"author")});z.ms.prototype.eK=z.Y(445,function(){return z.J(this,"author")});z.ks.prototype.KC=z.Y(444,function(){return z.J(this,"highlightId")});z.ks.prototype.Qs=z.Y(443,function(a){return z.K(this,"state",a)});z.ms.prototype.Qs=z.Y(442,function(a){return z.K(this,"state",a)});z.wx.prototype.Qs=z.Y(441,function(a){return z.K(this,"state",a)});
z.ks.prototype.vg=z.Y(440,function(){return z.J(this,"noteId")});z.ms.prototype.vg=z.Y(439,function(){return z.J(this,"noteId")});z.Cx.prototype.vg=z.Y(438,function(){return z.J(this,"noteId")});z.Fr.prototype.uv=z.Y(437,function(a){return z.K(this,"authorId",a)});z.ks.prototype.uv=z.Y(436,function(a){return z.K(this,"authorId",a)});z.ms.prototype.uv=z.Y(435,function(a){return z.K(this,"authorId",a)});z.bq.prototype.Me=z.Y(343,function(){return z.J(this,"catalogId")});
z.BK.prototype.Me=z.Y(342,function(){return z.J(this,"catalogId")});z.sK.prototype.Me=z.Y(341,function(){return z.J(this,"catalogId")});z.qK.prototype.Me=z.Y(340,function(){return z.J(this,"catalogId")});z.pM.prototype.Me=z.Y(339,function(){return z.J(this,"catalogId")});z.XJ.prototype.Me=z.Y(338,function(){return z.J(this,"catalogId")});z.VL.prototype.Me=z.Y(337,function(){return z.J(this,"catalogId")});z.QK.prototype.Me=z.Y(336,function(){return z.J(this,"catalogId")});
z.NL.prototype.Me=z.Y(335,function(){return z.J(this,"catalogId")});z.ML.prototype.Me=z.Y(334,function(){return z.J(this,"catalogId")});z.LL.prototype.Me=z.Y(333,function(){return z.J(this,"catalogId")});z.Fr.prototype.Me=z.Y(332,function(){return z.J(this,"catalogId")});z.Cx.prototype.Me=z.Y(331,function(){return z.J(this,"catalogId")});z.KH.prototype.Me=z.Y(330,function(){return z.J(this,"catalogId")});z.Wo.prototype.RT=z.Y(83,function(){return z.J(this,"point")});var C5a=/(?:https?:\/\/|www\.)\w[\w~#-@![\]]*/g;
B7.prototype.RT=function(){var a=window.document.body;return z.vg(a,this.mi.node)?this.mi:this.Rk&&z.vg(a,this.Rk)?z.bN(this.rQ,this.Rk):this.Qe&&(a=z.Fs(this.Bsa,this.Qe))?z.bN(this.rQ,a):null};z.q(D7,z.Zm);D7.prototype.zL=function(){if(!this.lk)return null;var a=this.lk.RT();if(!a)return null;var b=this.rm.RT();return b?z.An(a.node,a.offset,b.node,b.offset):null};z.q(E7,z.L);z.f=E7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.eb=function(){return z.J(this,"content")};
z.f.hd=function(a){return z.K(this,"content",a)};z.f.Ib=function(){return z.J(this,"title")};z.f.Rc=function(a){return z.K(this,"title",a)};z.f.eK=function(){return z.J(this,"author")};z.f.sv=function(a){return z.K(this,"author",a)};z.f.getDate=function(){return z.J(this,"date")};z.f.setDate=function(a){return z.K(this,"date",a)};z.f.Hb=function(){return z.J(this,"collection")};z.f.setVersion=function(a){return z.K(this,"version",a)};z.f.gM=function(a){return z.K(this,"template",a)};
z.f.Zd=function(){return z.J(this,"subtitle")};z.f.Ef=function(a){return z.K(this,"subtitle",a)};z.f.ha=function(){return E7.prototype};
z.f.fa={name:"TextshotInfo",ia:!1,fields:{content:{name:"content",g:z.V,h:1},altText:{name:"altText",g:z.V,h:2},title:{name:"title",g:z.V,h:3},author:{name:"author",g:z.V,h:4},date:{name:"date",g:z.V,h:5},authorAvatarId:{name:"authorAvatarId",g:z.V,h:6},collection:{name:"collection",g:z.V,h:7},collectionAvatarId:{name:"collectionAvatarId",g:z.V,h:8},collectionLogoId:{name:"collectionLogoId",g:z.V,h:9},collectionBackgroundColor:{name:"collectionBackgroundColor",g:z.V,h:10},collectionHighlightColor:{name:"collectionHighlightColor",
g:z.V,h:11},version:{name:"version",g:z.W,h:12},base64:{name:"base64",g:z.TH,h:13},template:{name:"template",g:z.V,h:14},mainStat:{name:"mainStat",g:z.V,h:15},mainStatTitle:{name:"mainStatTitle",g:z.V,h:16},subtitle:{name:"subtitle",g:z.V,h:17},icon:{name:"icon",g:z.V,h:18},imgKey:{name:"imgKey",g:z.V,h:19}},ka:{}};var S6a={DSa:"quote-respond"};z.q(G7,z.Q);z.f=G7.prototype;z.f.Ak=function(){return this.ym.Ak()};
z.f.na=function(){G7.xa.na.call(this);z.kx(this,this.u_,"data-redirect-type-quote",this.Xva,this);this.Ta(this.Vd,"click",this.Bw,this);z.iF(this.fb)&&z.nw()&&this.Ta(this.Vd,"mouseover",this.rta,this);this.fb.Za().Wr()&&!this.fb.Ob()&&z.v(this.we.load(this.fb.Na()),z.ex);var a=this.Ak();a&&(z.kx(this,a,"quote",this.ota,this),z.kx(this,a,"quote-respond",this.pta,this),z.kx(this,a,"show",this.s3,this),z.kx(this,a,"hide",this.qwa,this))};
z.f.Xva=function(a){var b=z.RE(this.ym,this.Ak().vx);b&&(a.url=new z.ie(this.ma.la(z.qCa,{postId:this.fb.Na()},{paragraphs:JSON.stringify([b.sy.Jb().Pb()]),startOffset:b.start,endOffset:b.end})))};z.f.Bw=function(a){z.Cs(a.target,function(a){if(a===this.Vd)return!0;var c=z.UB(a);if(3==c)return!0;if(7==c){if(c=M5a(this,a))if(H7(this,c),z.nw())J7(this,c);else{var d=new z.TE;K5a(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.rta=function(a){z.Cs(a.target,function(a){if(a===this.Vd)return!0;var c=z.UB(a);if(3==c)return!0;if(7==c){c=z.Nn();if(!(c&&!c.isCollapsed()||this.Ak()&&this.Ak().Ym())&&(c=M5a(this,a))){var d=this.Vd.querySelector('.markup--quote[name~\x3d"'+c.Xi()+'"]');a=new z.VE(a,100);K5a(this,c,d,a);H7(this,c)}return!0}return!1}.bind(this))};
z.f.s3=function(){var a=z.Nn();a&&!a.isCollapsed()&&H7(this,null);if(z.iF(this.fb)&&(a=z.RE(this.ym,this.Ak().vx))){var a=z.nva(this.we,a.sy,a.start,a.end),b=this.Ak().Sa().querySelector(".js-highlightMenuQuoteButton");z.yd(b,"is-active",!!a)}};z.f.qwa=function(){this.Gp&&H7(this,null)};
z.f.ota=function(){if(z.iF(this.fb)){var a=z.ME(this.Ak());if(a){var b=a.range,c=a.OHa,a=this.Ak().Sa().querySelector(".js-highlightMenuQuoteButton"),d=z.sd(a,"is-active"),b=z.RE(this.ym,b);z.v(z.t(this.we.toggle(b.sy,b.start,b.end,!c),function(a){z.QJa();d?z.OE(this.Ak()):J7(this,a);var b=c?"selection_menu":"quote_click_menu";K7(this,a.Xi(),!d,b)},this),z.ex)}}};
z.f.pta=function(){if(z.iF(this.fb)&&z.Mm.supportsEdit){var a=z.ME(this.Ak());if(a){var b=z.RE(this.ym,a.range);z.v(z.t(this.we.create(b.sy,b.start,b.end,1,!0),function(a){K7(this,a.Xi(),!0,"selection_menu_quote_respond");this.za("quote-respond",a,b.sy.name)},this),z.ex)}}};
z.f.yta=function(a){var b=this.Gp,c=I7(this,b),d=b.Dd(),e=b.Ae(),b=a.query(".js-quoteAttributions-pileOn"),g=z.sd(b,"is-active");z.v(z.t(this.we.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.zd(l,"is-active");if(l=z.IE(this.we,c,d,e)){var p=J5a(this,l),r=a.query(".js-quoteAttributions-info");z.jw(r,B5a,p)}else a.Mc();!g&&z.nw()&&(a.Mc(),J7(this,l));l=z.nw()?"quote_hover":"quote_click_mobile";K7(this,b.Xi(),!g,l)},this),z.ex)};
z.f.zta=function(){if(z.iF(this.fb)&&z.Mm.supportsEdit){var a=I7(this,this.Gp),b=this.Gp.Dd(),c=this.Gp.Ae();z.v(z.t(this.we.create(a,b,c,1,!0),function(b){K7(this,b.Xi(),!0,"quote_respond");this.za("quote-respond",b,a.name)},this),z.ex)}};z.f.Ata=function(){var a=O5a(this,this.Gp);a&&z.xva(this.ym,a)};
z.f.Pea=function(){var a=new D7(this.Vd),b=this.we.$t,c=Object.keys(b).concat(this.oba);z.fb(c);c.forEach(function(a){var c=b[a]||[],g=this.fb;if(g=(a=g.Vd&&z.Fs(g.Vd,a))&&this.fb.Wi(a))A5a(g,c),a.innerHTML=z.Vt(g,z.Mm,z.Nva(this.fb)),z.eya(this.fza,a)},this);this.oba=Object.keys(b);(a=a.restore())&&a.select()};z.q(L7,z.ix);z.f=L7.prototype;
z.f.load=function(a){if(!z.nq())return z.fd([]);this.ob=a;this.Gh||(this.Gh=z.v(z.t(this.ol.get(this.ma.la(z.iCa,{postId:a}),{background:!0}),this.dza,this),z.ex));return this.Gh.Xc()};z.f.cq=function(){return this.lba};z.f.Kj=function(){return this.lea};z.f.xT=function(a){return this.Bca[a]||null};z.f.Up=function(a,b){return z.KN(M7(this,b),a)};z.f.dz=function(a,b){this.Bca[a]=b};z.f.Na=function(){return this.ob};
z.f.dza=function(a){var b=a.references.User;this.lea=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,k=b;if(g)for(var l=0;l<g.length;l++){var p=g[l],r=p.authorId||null;p.author=r&&k[r]||null}g=e.anchor;k=e.authorId||null;e.author=k&&b[k]||null;g=M7(this,g);e=z.ls(e);g.add(z.EC(this.Aa,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.dz(a[b].id,z.Oo.Jb(z.ns,a[b]));this.lba=!0};z.m(P7,z.Q);P7.prototype.na=function(){var a=this;z.Q.prototype.na.call(this);z.t(this.ib.QT(this.Wza,this.Rya),function(b){b.placements&&b.placements.forEach(a.mua,a)})};P7.prototype.mua=function(a){if(this.isActive()){var b;switch(a.location){case 1:b=this.Oa.query(".js-postFooterPlacements");if(!b)break;z.jw(b,z.wQ,{items:a.items,context:9});z.T(b).ba("show-more-recommendations",this.CBa,this);break;case 2:(b=this.Oa.query(".js-readNextMetabarRight"))&&z.jw(b,z.wQ,{items:a.items,context:2})}}};
P7.prototype.CBa=function(a){z.Hx(z.XFa,{});var b=this.Oa.query(".js-moreRecommendations");b&&(z.Is(b),z.Hs(a.target))};z.m(Q7,z.Q);z.f=Q7.prototype;
z.f.na=function(){var a=this;z.Q.prototype.na.call(this);this.sp&&(z.kx(this,this.sp,z.FGa,function(){z.td(a.oa(),"is-abovePostActions");a.RP=!0}),z.kx(this,this.sp,z.GGa,function(){z.wd(a.oa(),"is-abovePostActions");a.RP=!1}));z.T(this.oa()).ba("dismiss-meter",this.st,this).ba("expand-meter",this.vsa,this);var b=this.lh.postIds&&1<this.lh.postIds.length,c=z.dq().isMobile&&!z.dq().isTablet;if(b||c)this.fw=(0,window.setTimeout)(this.st.bind(this),T6a);z.t(z.Vm(300),this.Eza,this)};
z.f.Ca=function(){this.gh&&(this.gh.cancel(),this.gh=null);this.fw&&((0,window.clearTimeout)(this.fw),this.fw=null);z.Q.prototype.Ca.call(this)};z.f.st=function(){var a=this;this.gh=new z.zA(this.oa(),{name:this.RP?z.dq().isMobile?"pop-shift-down-35":"pop-shift-down-44":"pop-shift-down-0",duration:550,timing:"ease-in-out"});z.t(this.gh,function(){z.Hs(a.oa());z.Is(a.Oa.query(".js-openInAppButton"))});this.gh.start()};
z.f.vsa=function(a){a=a.target;var b=this.query(U6a),c=this.query(V6a);z.Hs(a);z.td(b,"is-visible");this.fw&&((0,window.clearTimeout)(this.fw),this.fw=null);z.jw(c,z.Dwa);z.wd(c,"u-xs-hide");z.Hx(z.eGa,{unlockCount:this.lh.postIds.length})};
z.f.Eza=function(){var a=this;this.Oa.oa().appendChild(this.oa());z.t((new z.zA(this.oa(),{name:this.RP?z.dq().isMobile?"pop-shift-up-35":"pop-shift-up-44":"pop-shift-up-0",duration:800,timing:"ease-in-out"})).start(),function(){if(a.lh&&a.lh.postIds&&a.lh.postIds.length){for(var b=a.sb(".js-meterThumbnail"),c=new z.Tc,d=0;d<a.lh.postIds.length;d++)z.t(c,a.sY.bind(a,b[d],d==b.length-1));c.callback()}})};
z.f.sY=function(a,b){b=new z.zA(a,{name:b?"pulse-grow-50-110":"pulse-grow-50-105",duration:800+(b?200:0)});var c=z.t(new z.zA(a.querySelector(".js-thumbnailImage"),{name:"fade-in",duration:800}),function(){z.td(a,"is-read")}),d=new z.zA(a.querySelector(".js-thumbnailText"),{name:"color-light-to-white",duration:800});return new z.Nm([b.start(),c.start(),d.start()])};var T6a=6E3,V6a=".js-dismissMeterIndicator",U6a=".js-moreInfo";R7.prototype.VS=function(a,b,c){return new G7(a,b,c)};R7.prototype.bs=function(){return S6a};c6a.prototype.get=function(a){return S7(this,a)};z.q(T7,z.dW);z.f=T7.prototype;z.f.XI=!1;z.f.cB="";z.f.YI=0;z.f.rs=z.U;z.f.vg=function(){return this.W0};z.f.save=function(){this.eb().length<=this.xm&&this.rl()};z.f.Gb=function(){(0,window.clearTimeout)(this.YI);T7.xa.Gb.call(this)};
z.f.na=function(){function a(a){a.stopPropagation()}T7.xa.na.call(this);this.cB=this.eb();this.hd(this.cB);this.Jx(13,this.$0,this);this.Jx(27,this.a1,this);this.Ab.Ta("blur",this.Z0,!1,this);var b=this.Ab.Sa();z.yw(b,"keydown",a);z.yw(b,"keyup",a);z.yw(b,"keypress",a)};z.f.J7=function(a){return a};
z.f.rl=function(){if(this.isEnabled()){var a=this.eb().trim();if(a){this.$V(!1);var b=this.eia(),a=this.dia(a);this.za("saving",a);z.Yc(z.v(z.t(this.ol.post(b,a.Pb()),this.Rwa,this),this.Pwa.bind(this,a)),this.$V.bind(this,!0))}}};z.f.Rwa=function(a){this.za("save",this.J7(a.value))};z.f.Pwa=function(a,b){this.za("fail",a);this.Fa.error(f6a());z.ex(b)};z.f.$0=function(a){if(this.Fr&&z.LX(this.Fr))return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.a1=function(a){if(this.Fr&&z.LX(this.Fr))return!1;a.preventDefault();this.hd(this.cB);this.za("cancel");return!1};z.f.Z0=function(){this.XI&&(this.eb().length>=this.xm?(0,window.confirm)(this.hia())?(this.hd(this.cB),this.za("cancel")):this.focus():this.YI=(0,window.setTimeout)(this.rl.bind(this),100))};z.q(U7,T7);z.f=U7.prototype;z.f.pY=null;z.f.Faa=null;z.f.qY=null;z.f.fk=null;z.f.P_=null;z.f.O_=null;z.f.Aca=null;z.f.dz=function(a){this.fk=a;this.P_=a.startIndex;this.O_=a.endIndex;this.Aca=a.content;return this};z.f.hia=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};z.f.J7=function(a){var b=z.hw();a=z.ls(a).sv(b).uv(b.nb());this.fk&&a.KC()&&this.yf.dz(a.KC(),this.fk);var b=this.yf,c;c=z.EC(b.Aa,a);M7(b,c.ie()).add(c);return a};
z.f.eia=function(){return this.vg()?this.ma.la(z.jCa,{postId:this.ob,noteId:this.vg()}):this.ma.la(z.hCa,{postId:this.ob})};z.f.dia=function(a){var b=z.hw();a=(new z.ks({content:a,anchor:this.pY,anchorContent:this.Faa,anchorImage:this.qY?this.qY.Pb():null,replies:[],createdAt:Date.now()})).sv(b);null!=this.P_&&null!=this.O_&&(b=new z.ns({anchor:this.pY,startIndex:this.P_,endIndex:this.O_,content:this.Aca}),a.dz(b));return a};z.q(V7,T7);V7.prototype.hia=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};V7.prototype.J7=function(a){var b=z.hw();a=z.hja(a).sv(b).uv(b.nb());z.J(this.yf.Up(a.vg(),this.Qe),"replies").push(a);return a};V7.prototype.eia=function(){return this.Lea?this.ma.la(z.mCa,{postId:this.ob,noteId:this.vg(),replyId:this.Lea}):this.ma.la(z.lCa,{postId:this.ob,noteId:this.vg()})};
V7.prototype.dia=function(a){var b=z.hw();return(new z.ms({replyId:"",postId:this.ob,noteId:this.vg(),content:a,createdAt:Date.now()})).sv(b)};z.q(X7,z.Q);z.f=X7.prototype;
z.f.na=function(){X7.xa.na.call(this);z.T(this.oa()).ba("show-note-editor",this.N2,this).ba("hide-note-editor",this.L_.bind(this,!0)).ba("show-reply-editor",this.QBa,this).ba("hide-reply-editor",this.Wta,this).ba("save-note",this.vAa,this).ba("save-reply",this.wAa,this).ba("highlight-quote",this.Zta,this).ba("dismiss-note",this.sba.bind(this,!0),this).ba("delete-note",this.sba.bind(this,!1),this).ba("delete-reply",this.Kra,this).ba("previous-highlight-tip",this.bza,this).ba("next-highlight-tip",this.zva,
this);t6a(this);this.zj&&t7(this.zj)&&(s6a(this),z.kx(this,t7(this.zj),"add",this.Owa,this));if(this.T1&&this.Nca&&this.Oca){var a=this.query(".js-inlineNewPostControl"),b=this.T1,c=this.fb.Na(),d=new z.WW(this.qa);d.XL("web-inline-quote-responses");d.Wa(a);d.yG=!0;d.wZ=!0;d.tZ=!0;d.gM(D5a);d.bB=b;d.aM(c);z.XW(d,!0);this.Ic=d;this.Ic.ua();a=Z7(this.yI);this.za("set-active-highlight",this.Qe,a)}this.fk&&(this.N2(),this.Pf&&this.Pf.focus());$7(this,0)};
z.f.Ca=function(){this.$q&&this.$q.L4();(this.fk||this.yI)&&this.za("reset-highlight",this.Qe,null);X7.xa.Ca.call(this)};z.f.Gb=function(){z.Ox(this.oa());z.og(this.oa());z.Qm(this.Ic);z.Qm(this.Pf);z.Qm(this.$q);z.Rm(z.rb(this.hk));this.$q=this.hk=this.Pf=this.Ic=null;X7.xa.Gb.call(this)};z.f.uo=function(){if(this.Pf&&this.Pf.eb())return!0;for(var a=z.rb(this.hk),b=0;b<a.length;b++)if(a[b]&&a[b].eb())return!0;return this.Ic&&!this.Ic.isDismissable()?!0:!1};
z.f.Sq=function(){var a=[],b=[],c=[],d=this.hB&&(this.fk||this.yI);d||(this.Iw?(a=this.we?u7(this.we,this.Iw.quotes):[],b=this.Iw.notes,c=this.Iw.responses):(b=this.yf?z.iD(M7(this.yf,this.Qe)):[],this.W0||(this.we?(a=this.we,a=u7(a,a.$t[this.Qe]||[])):a=[],c=this.zj?A7(this.zj,this.Qe):[])));return z.lw(p6a,{post:this.fb.Za(),quotes:a,notes:b,responses:c,p9:!!this.T1,fW:d,kM:this.hB,qE:this.Sfa,FIa:z.hF(this.fb)})};
z.f.Owa=function(){var a=this.query(".js-postList"),b=z.lw(o6a,{responses:A7(this.zj,this.Qe)});z.pg(b,a);s6a(this)};
z.f.N2=function(){if(this.hB){if(!this.Pf){var a=this.query(".js-noteEditor"),b=z.kw(m6a),a=this.Pf=new U7(this.qa,a,this.fb.Na(),null,b),b=this.Qe,c=this.fb.Wi(this.mf.get(this.Qe)),d=c.Ia(),c=4==c.type?c.Be():null;a.pY=b;a.Faa=d;a.qY=c;(a=this.fk)&&this.Pf.dz(a);z.kx(this,this.Pf,"saving",this.vxa,this);z.kx(this,this.Pf,"fail",this.owa,this);z.kx(this,this.Pf,"save",this.qxa,this)}z.td(this.query(".js-noteActions"),"is-noteEditorVisible");this.Pf&&this.Pf.focus()}};
z.f.vAa=function(){this.Pf&&this.Pf.save()};z.f.vxa=function(a){this.Pf.hd("");var b=this.query(".js-notesList");a={note:a,post:this.fb.Za(),fW:this.hB,kM:this.hB};a=z.lw(W7,a);b.appendChild(a);z.wd(b,"is-empty");t6a(this);this.L_()};z.f.qxa=function(a){var b=this.query(".js-notesList").lastChild;a=a.vg();z.td(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.owa=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.td(a,"is-empty");this.N2()};z.f.L_=function(a){a?this.za("close"):this.Pf&&(this.Pf.eb()&&this.Pf.hd(""),z.wd(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.QBa=function(a){(a=Y7(a.target))&&this.hB&&u6a(this,a)};z.f.wAa=function(a){a=Y7(a.target);(a=this.hk[a])&&a.save()};
z.f.wxa=function(a){var b=a.vg();this.hk[b]&&this.hk[b].hd("");var c=this.yf.Up(b,this.Qe).author.userId==a.author.userId,d=this.query(".js-note-"+a.vg()+" .js-repliesList");a={note:a,post:this.fb.Za(),sja:c};a=z.lw(W7,a);d.appendChild(a);z.wd(d,"is-empty");v6a(this,b)};z.f.rxa=function(a){var b=this.query(".js-note-"+a.vg()).querySelector(".js-repliesList").lastChild;a=a.ly();z.td(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.pwa=function(a){var b=this.query(".js-note-"+a.vg()+" .js-repliesList");b.removeChild(b.lastChild);z.td(b,"is-empty");u6a(this,a.vg())};z.f.Wta=function(a){(a=Y7(a.target))&&v6a(this,a)};z.f.Zta=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=S7(this.mf,this.Qe);c&&(this.$q&&this.$q.L4(),this.$q=x6a(this,c,a,function(){w6a(this,b,!1);z.Qm(this.$q);this.$q=null}),w6a(this,b,!0))};
z.f.Yta=function(a){var b=S7(this.mf,this.Qe);(a=this.yf.Up(a.target.getAttribute("data-note-id"),this.Qe))&&b&&(b=(b=a.KC())?this.yf.xT(b):null,this.za("set-active-highlight",this.Qe,b))};z.f.$ta=function(a){var b=S7(this.mf,this.Qe),c;c=this.zj;a=a.target.getAttribute("data-post-id");c=t7(c)?z.KN(t7(c),a):null;b&&c&&(b=y7(c))&&(b=z7(b)&&z7(b).lo())&&(c=b.gc())&&c.length&&(b=Z7(b),this.za("set-active-highlight",this.Qe,b))};
z.f.q3=function(){var a=null;this.yI&&(a=Z7(this.yI));this.fk&&(a=this.fk);this.za("reset-highlight",this.Qe,a)};
z.f.sba=function(a,b){b=b.value;var c=this.yf.Up(b,this.Qe),d=this.query(".js-note-"+b);if(c&&d){z.Hs(d);this.q3();this.sb(".js-note-item").every(function(a){return z.sd(a,"u-hide")})&&this.L_(!0);var e=N7(this.yf,c,"HIDDEN");z.v(e.Gl,function(b){this.ya.ua(a?g6a():h6a(),"error");e.EL();z.Is(d);(400>b.status||499<b.status)&&N7(this.yf,c,"NEW")},this);z.t(this.ya.ua(a?j6a():k6a(),{type:"success",rE:!0}),function(){this.ya.Mc();e.EL();N7(this.yf,c,"NEW");z.Is(d)},this)}};
z.f.Kra=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=Y7(a.target);if(d&&c){z.Hs(c);var e=O7(this.yf,b,d,this.fb.Na(),this.Qe,"HIDDEN");z.v(e.Gl,function(){this.ya.ua(i6a(),"error");e.EL();z.Is(c);O7(this.yf,b,d,this.fb.Na(),this.Qe,"")},this);z.t(this.ya.ua(l6a(),{type:"success",rE:!0}),function(){this.ya.Mc();e.EL();O7(this.yf,b,d,this.fb.Na(),this.Qe,"");z.Is(c)},this)}};z.f.bza=function(){$7(this,this.zP-1)};z.f.zva=function(){$7(this,this.zP+1)};z.q(a8,z.Q);z.f=a8.prototype;z.f.na=function(){a8.xa.na.call(this);var a=[];z.hF(this.fb)&&a.push(this.yf.load(this.ob));this.Tca||(a.push(this.we.load(this.ob)),a.push(this.zj.load(this.ob)));this.pw=z.t(z.t(z.t(z.NR(a),function(){this.pw=null},this),this.render,this),this.Hqa,this);z.kx(this,this.Db,"resize-end",this.Wf,this)};z.f.Ca=function(){this.pw&&this.pw.cancel();a8.xa.Ca.call(this)};z.f.Gb=function(){this.pw=null;a8.xa.Gb.call(this)};
z.f.render=function(){d6a(this.mf,function(a,b){b8(this,b)},this)};z.f.Wf=function(){d6a(this.mf,function(a,b){E6a(this,b)},this)};z.f.Hqa=function(){var a=this.we.vp;z.kx(this,a,"add",this.Vda,this);z.kx(this,a,"remove",this.Vda,this);(a=t7(this.zj))&&z.kx(this,a,"add",this.nxa,this)};z.f.Vda=function(a){y6a(this,Object.keys(z.rva(this.we,a instanceof Array?a:[a])))};z.f.nxa=function(a){y6a(this,(a instanceof Array?a:[a]).map(this.zj.z5,this.zj))};
z.f.Sq=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};z.f.YH=function(a,b){z.Db(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.q(c8,z.Q);z.f=c8.prototype;
z.f.na=function(){c8.xa.na.call(this);this.Ta(this.Oa.oa(),"click",this.bva,this,!0);z.T(this.VH).ba("select-anchor",this.Cxa,this);var a=this.fb.Za();if(a.Wr()&&!this.fb.Ob()){var b=z.Vp(a),b=2==a.visibility&&b&&!z.J(b.Oj(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.v(this.zj.load(this.fb.Na(),"best"),z.ex);z.v(this.we.load(this.fb.Na()),z.ex)}a.Oj().dK()&&(this.pQ=z.t(this.yf.load(this.fb.Na()),this.Swa,this));this.A0&&e8(this,null);z.kx(this,this.rb,"historyUpdate",function(){e8(this,
z.XE())},this);this.Se&&z.kx(this,this.Se,"highlight",this.Qwa,this)};z.f.Gb=function(){z.Qm(this.Kh);this.Kh=null;z.Qm(this.lm);this.lm=null;this.VH&&z.T(this.VH).clear("select-anchor");this.pQ&&this.pQ.cancel();this.pQ=null;c8.xa.Gb.call(this)};z.f.MIa=function(a,b){d8(this,b,null,null,a)};z.f.KKa=function(){this.Kh&&this.Kh.Wf()};z.f.uo=function(){if(!this.lm)return!1;var a=this.lm.eb();return a?a.uo():!1};z.f.Nwa=function(a){a.subscribe("add",this.aga,this);a.subscribe("remove",this.aga,this)};
z.f.aga=function(a){(z.oa(a)?a:[a]).forEach(function(a){b8(this.Kh,a.ie())},this)};z.f.Swa=function(){var a=(0,z.Ka)();this.pQ=null;e8(this,z.XE());this.Ta(this.mm,z.zI,this.k1,this);z.yy(z.BEa,(0,z.Ka)()-a)};z.f.k1=function(a){(a=a.target.getAttribute("name"))&&S7(this.mf,a)&&E6a(this.Kh,a)};z.f.Qwa=function(){if(this.Se){var a=K6a(this,this.Se.vx);z.OE(this.Se);a&&(a=a.highlight,this.afa(a.anchor,a),d8(this,a.anchor,a))}};
z.f.bva=function(a){if(this.lm){var b=a.target;if(!z.vg(this.lm.oa(),b)){var c=this.lm.eb(),d;if(!(d=!c)){a:if(c.Pf&&c.Pf.eb())c=!0;else{d=z.rb(c.hk);for(var e=0;e<d.length;e++)if(d[e]&&d[e].eb()){c=!0;break a}c=c.Ic&&!c.Ic.Zi()?!0:!1}d=!c}d&&(c=this.lm&&this.lm.Qn,d="select-anchor"==b.getAttribute("data-action"),this.c2(),c&&d&&z.vg(c,b)&&a.stopPropagation())}}};
z.f.Kn=function(a){if(!z.pw()){var b=a.Qn,c=z.Jw(b);a.Ll();a=a.oa();var d=z.Jw(a),e=window.innerHeight,g=window.innerWidth,k=this.Oa.query(".js-metabar"),l=0;k&&(l=z.Jw(k).height);d.height>=e-l?R5a(a):(z.Fw(b),b=c.top+d.height>=e?z.Gw().top+e-d.height-10:z.Fw(b),c=z.Jw(this.VH).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.c2=function(){z.Qm(this.lm);this.lm=null};
z.f.Cxa=function(a){var b=z.Cs(a.target,function(a){return z.sd(a,"js-paragraphControl")},this.eea),b=F6a(this.Kh,a.value,b);d8(this,a.value,null,null,null,b)};z.f.afa=function(a,b){if(this.fb.Ob()){var c=z.Nn();this.iR=(c=c&&e6a(this.mf,c.Uf()))&&new D7(c)}J6a(this,a,b)};z.f.dAa=function(a,b){J6a(this,a,b);this.fb.Ob()&&this.iR&&(a=this.iR.restore())&&a.select();this.iR=null};
z.f.ix=function(a){if(this.mf&&(a=S7(this.mf,a))){a=Math.max(z.Fw(a),0);var b=window.document.body;this.gh&&this.gh.cancel();this.gh=new z.Mo(b,"scrollTop",600,a)}};L6a.prototype.VS=function(a,b,c){return new c8(a,b,c)};z.m(f8,z.Q);z.f=f8.prototype;z.f.Dc=function(a){this.va=a};z.f.gM=function(a){this.Oh=a};z.f.PJa=function(a){this.I2=a};z.f.QJa=function(a){this.nfa=a};
z.f.na=function(){this.oa()?(z.Q.prototype.na.call(this),z.T(this.oa()).ba("show-responses-stream-editor",this.Oxa,this).ba("show-other-responses",this.tfa,this),z.jw(this.oa(),this.Oh,{post:this.va}),this.va.Wr()&&z.v(z.t(z.t(z.t(z5a(this.ib,this.va.Cb(),"best"),this.Jea.bind(this,"best")),this.Lza,this),function(){this.A3.N8&&this.tfa()},this),z.ex)):z.ex("Attempted to initialize ResponsesStreamControl without root element.")};z.f.Ca=function(){z.T(this.oa()).clear("show-other-responses");z.Q.prototype.Ca.call(this)};
z.f.Jea=function(a,b){this.isActive()&&(b=b.Pe,"best"==a?(a=this.query(".js-responsesStream"),z.kx(this,b,"add",this.wda.bind(this,b)),this.wda(b)):a=this.query(".js-responsesStreamOther"),b&&(z.Oq()||0<b.Ne())&&a&&(z.jw(a,z.wQ,{items:z.iD(b),context:2}),b=new z.AS(this.qa,b),b.Wa(a),b.Ad(2),this.track(b),z.Is(this.query(".js-responsesStreamWrapper"))),this.nfa&&(a=z.Fw(a),z.Cw(window.document.body,0,a)))};
z.f.Lza=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.Oq()?a?(this.Ic=z.XW(t5a((new z.WW(this.qa)).XL("web-inline-post-response").aM(this.va.Cb()),z.iw(z.Ei,{post:this.va,QV:!0})),this.I2).Wa(a),this.track(this.Ic)):b&&this.I2&&(a=z.Ew(b),b=z.Fw(b),z.Cw(a,0,b)):b&&z.td(b,"u-hide")};
z.f.tfa=function(){this.o1||(this.o1=z.Yc(z.t(z.t(z5a(this.ib,this.va.Cb(),"other"),this.Jea.bind(this,"other")),function(){z.Hs(this.query(".js-showOtherResponses"));this.A3.N8=!0},this),function(){this.o1=null},this))};z.f.wda=function(a){(a=a.hl)&&a.next&&"other"==a.next.filter&&!this.A3.N8&&(z.Is(this.query(".js-responsesStreamWrapper")),z.Is(this.query(".js-showOtherResponses")))};z.f.Zx=function(){this.Ic&&(z.AR(this.Ic.oa(),new z.Tn(60,0,200,0)),this.Ic.Zx())};
z.f.Oxa=function(){var a=this.query(".js-responsesStreamEditor"),b=this.query(".js-showResponsesStreamEditorButton");z.Js(a)&&(z.Is(a),z.Hs(b),this.Zx())};z.q(g8,z.ix);g8.prototype.focus=function(){this.isActive&&this.uz.focus()};g8.prototype.close=function(){this.uz&&!this.uz.closed&&this.uz.close();this.za("close");this.dg()};g8.prototype.isActive=function(){return this.uz?!this.uz.closed:!1};g8.prototype.Va=function(){this.uz=null;g8.xa.Va.call(this)};z.f=N6a.prototype;z.f.fE=function(a,b,c){var d;d=z.Mm;var e=new z.Di(z.Lm(d)),e=new z.ie(e.Al(a));d=F7(e,d);this.Sw(d);z.Hx(z.jJ,{postId:a.id,type:b,source:c,dest:"facebook",dialogType:"native"})};z.f.G8=function(a){var b;b=z.Mm;var c=new z.Di(z.Lm(b));a=new z.ie(c.la(z.Ev,{catalogSlug:a.Me(),username:a.Bf().Dk()}));b=F7(a,b);this.Sw(b)};z.f.H8=function(a){var b;b=z.Mm;var c=new z.Di(z.Lm(b));a=new z.ie(c.la(z.vv,{sequenceSlug:a.td()}));b=F7(a,b);this.Sw(b)};
z.f.u5=function(){var a=this.ma.la(z.PBa);return this.pa.get(a)};z.f.Sw=function(a){M6a(a,"facebook-share",{width:550,height:320})};z.q(h8,z.Om);
h8.prototype.open=function(a,b){this.va=a;this.zx=b;this.Fa=this.wG.open({bodyHtml:z.iw(W5a,this.zx),type:"tweet"},!0);a=this.Fa.query(".js-tweetEditor-text");b=this.qa;var c=String,d;d=z.n("Enter tweet text.");d=(0,z.y)(""+d);this.wJ=new z.HX(b,a,c(d),!0);a=new z.zW(280,!0);a.gba=C7;this.wJ.bb(a);a=F5a(S5a,this.zx,z.Mm);this.wJ.hd(a);this.wJ.focus();P6a(this);z.T(this.Fa.ac).ba("remove-textshot",this.ffa.bind(this,!1),this).ba("add-textshot",this.ffa.bind(this,!0),this).ba("toggle-expand-image",this.JCa,
this);this.Fa.subscribe(z.Zy,this.wDa.bind(this))};h8.prototype.wDa=function(){var a=this.wJ.eb();if(Q6a(this,a)){var b=this.EP?O6a(this):null;z.v(z.t(this.pa.post(this.ma.la(z.NBa),{tweet:a,textshotInfo:b}),function(a){a=z.kw(U5a,{id:a.value});a=z.iw(Y5a,{DKa:a});this.ya.ua(a,{type:"success",cm:1E4})},this),function(a){z.ex(a);this.ya.ua(X5a(),"error")},this);z.sy(z.qEa,{postId:this.va.id,type:this.zx.shareType,source:this.zx.UJa,dest:"twitter",style:this.EP?"textshot":null});this.Fa.close()}};
h8.prototype.ffa=function(a){this.EP=a;z.yd(this.Fa.query(".js-tweetEditor-imageContainer"),"u-hide",!a);z.yd(this.Fa.query(".js-tweetEditor-addTextshot"),"u-hide",a)};h8.prototype.JCa=function(){var a=this.Fa.query(".js-tweetEditor-image");z.zd(a,"tweetEditor-image--expanded")};z.f=R6a.prototype;z.f.TJa=function(a,b){var c=z.mq(),d=a.creator||{},e=y5a(b),g=x5a(b),k=G5a(a,z.Mm);(b=$5a(b.w5()))&&z.ne(k,b||"");var l={name:d.name||"",username:d.username||"",twitterScreenName:d.twitterScreenName||"",url:k.toString(),content:a.title,user:c,uKa:e,tKa:g,shareType:"highlight",UJa:"highlight_menu"};z.v(z.t(this.qa.load("tweet-dialog"),function(b){b.open(a,l)}),z.ex);z.sy(z.jJ,{postId:a.id,type:"highlight",source:"highlight_menu",dest:"twitter",dialogType:"inapp"});return!0};
z.f.fE=function(a,b,c,d,e){var g=z.mq().userId,k="highlight"==c?S5a:z.nja,l=z.Mm,p=a.creator||{};b={content:b,name:p.name||"",username:p.username||"",twitterScreenName:p.twitterScreenName||"",Jga:p.userId==g,url:G5a(a,l).toString(),collaborators:d||[]};d=d&&d.length?String(k(b,null,l)):F5a(k,b,l);k=new z.ie("https://twitter.com/intent/tweet");z.xe(k,"text",d);this.Sw(k);z.Hx(z.jJ,{postId:a.id,type:c,source:e,dest:"twitter",dialogType:"native"})};
z.f.G8=function(a){var b=z.Mm,c=new z.Di(z.Lm(b)),c=(new z.ie(c.la(z.Ev,{catalogSlug:a.Me(),username:a.Bf().Dk()}))).toString();a=z.B(""+z.dl(String(a.name))+((null==a.creator?null:a.creator.userId)!=b.currentUser.userId?" — "+z.ts({twitterScreenName:null==a.creator?null:a.creator.twitterScreenName,name:null==a.creator?null:a.creator.name}):"")+" "+(""+c));b=new z.ie("https://twitter.com/intent/tweet");z.xe(b,"text",a);this.Sw(b)};
z.f.H8=function(a){var b=new z.Di(z.Lm(z.Mm)),b=(new z.ie(b.la(z.vv,{sequenceSlug:a.td()}))).toString();a=z.B(""+z.dl(String(a.title))+" "+(""+b));b=new z.ie("https://twitter.com/intent/tweet");z.xe(b,"text",a);this.Sw(b)};z.f.Sw=function(a){M6a(a,"twitter-share",{width:670,height:420})};var W6a=z.by,X6a=W6a.Da();z.ey(X6a.scope("screen").add("quotes",R7).add("quote-responses",L6a).add("responses-stream-control",f8).add("notes-data",L7),"PostMeterBar",Q7);z.ey(X6a.scope("app"),"PlacementsControl",P7).add("twitter",R6a).add("facebook",N6a).add("tweet-dialog",h8);z.LN(W6a,"notes");}).call(this, _mdm);
