# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dbfced536004cc9072e71a421543aab5a5138b6391c2fd562b78b5f2b7de4da351566035a685a1cd25146fc86d488eb0fb5564e930e9085658208846812fd1e

test:
  secret_key_base: 153d5ce18d59464f6f687ba87b3653a41d36b329fe481e39f445382f4878946859ac322720cbf78cd1587fce40c08b24e41bf74668191a1bb7452823033d5997

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
